knp_snappy:
    pdf:
        enabled:    true
        binary:     '/usr/bin/wkhtmltopdf'
        options:    []
    image:
        enabled:    true
        binary:     '/usr/bin/wkhtmltopdf'
        options:    []
